---

- name: Build image
  hosts: "localhost"
  become: true
  vars:
    dockerid: "244342"
    dest: "/home/ansible/repo"
    repo: "https://github.com/Safrudin244342/angkringanhits-api.git"
    project: angkringanbackend

  tasks:
   - name: ensure docker installed
     yum:
      name: docker
      state: present
     tags: always

   - name: ensure python docker
     pip:
      name: docker
      state: present

   - name: ensure docker running
     service:
      name: docker
      state: started
      enabled: yes
     tags: always

   - name: ensure git installed
     yum:
      name: git
      state: present
     tags: always

   - name: ensure folder exits
     file: path={{ item }} state=directory
     with_items:
      - "{{ dest }}"
      - "{{ dest }}/{{ project }}"
     tags: ['never', 'setup']

   - name: clone repo
     git: 
      repo: "{{ repo }}"
      version: "{{ branch }}"
      dest: "{{ dest }}/{{ project }}/{{ branch }}"

   - name: remove image
     community.general.docker_image: "name={{ item }} state=absent"
     with_items:
      - "{{ dockerid }}/{{ project }}:latest"
      - "{{ dockerid }}/{{ project }}:{{ branch }}"

   - name: build image
     community.general.docker_image:
      name: "{{ dockerid }}/{{ project }}"
      build:
        path: "{{ dest }}/{{ project }}/{{ branch }}"
        pull: yes
      source: build

   - name: push image
     community.general.docker_image:
      name: "{{ dockerid }}/{{ project }}"
      repository: "{{ dockerid }}/{{ project }}:{{ branch }}"
      push: yes
      source: local